#!/usr/bin/env bash
# This script installs Nginx, configures a custom header for Nginx response,
# and sets up a custom 404 error page on an Ubuntu server.

# Install Nginx if it's not installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Set up the custom 404 page
sudo mkdir -p /var/www/html/errors
echo "Ceci n'est pas une page" | sudo tee /var/www/html/errors/404.html

# Update the default Nginx configuration
sudo sed -i '/server {/a \\tlocation = /errors/404.html { internal; }\n\terror_page 404 /errors/404.html;' /etc/nginx/sites-available/default

# Add the custom header to show the server hostname in responses
sudo sed -i '/server {/a \\tadd_header X-Served-By \"$hostname\";' /etc/nginx/sites-available/default

# Reload Nginx
sudo nginx -t && sudo service nginx reload
