#!/usr/bin/env bash
# This script transfers a file to a remote server's home directory using SCP with a private key and disables strict host key checking.

# Check if there are exactly 4 arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign command-line arguments to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Use scp to transfer the file with strict host key checking disabled
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
