#!/usr/bin/env bash
# This script transfers a file to a remote server's home directory using SCP with a private key and disables strict host key checking.

# Check if there are exactly 4 arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Use scp to transfer the file with strict host key checking disabled
scp -i "/root/.ssh/id_rsa.pub" -o StrictHostKeyChecking=no "alu-system_engineering-devops/web_servers/0-transfer_file" "ubuntu@18.206.168.44:~/"
